baseURL = 'https://flux6174.github.io/env/'
languageCode = 'en-US'
title = ' flux6174'

[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1
    [menus.main.params]
      image = 'digigarden2025.png'

  [[menus.main]]
    name = 'write'
    pageRef = '/write'
    weight = 2

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
